// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "Test/domain"

	mock "github.com/stretchr/testify/mock"
)

// BrandData is an autogenerated mock type for the BrandData type
type BrandData struct {
	mock.Mock
}

// CreateBrandData provides a mock function with given fields: newBrand
func (_m *BrandData) CreateBrandData(newBrand domain.Brand) domain.Brand {
	ret := _m.Called(newBrand)

	var r0 domain.Brand
	if rf, ok := ret.Get(0).(func(domain.Brand) domain.Brand); ok {
		r0 = rf(newBrand)
	} else {
		r0 = ret.Get(0).(domain.Brand)
	}

	return r0
}

type mockConstructorTestingTNewBrandData interface {
	mock.TestingT
	Cleanup(func())
}

// NewBrandData creates a new instance of BrandData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBrandData(t mockConstructorTestingTNewBrandData) *BrandData {
	mock := &BrandData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
